services:
  db:
    image: mariadb:10.6.4-focal
    container_name: wordpress_db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
    networks:
      - wordpress-network
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - 8000:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - wordpress-network
  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin:latest
    container_name: wordpress_phpmyadmin
    networks:
      - wordpress-network
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
networks:
  wordpress-network:
    driver: bridge
volumes:
  db_data:
